import time
from datetime import datetime, timedelta
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import pandas as pd
from db_login import enc, driver
import pyautogui 
from db_fiscais import abrev_nomes_joined
from db_arquivos import *

df = pd.read_csv(databaseCSV1)
enc()

today = datetime.today()
yesterday = datetime.today() + timedelta(days=-1)
today = today.strftime("%d/%m/%Y")
yesterday = yesterday.strftime("%d/%m/%Y")
time.sleep(5)

for i in df.index:    
    ra = str(df['RA'][i])
    fiscal = str(df['FISCAL'][i])
    if fiscal != '0':
        fiscal = abrev_nomes_joined["{}".format(fiscal)]
    qtd = str(df['LISTAGEM'][i])
    os = str(df['OS'][i])    
    
    pyautogui.hotkey('ctrl', 'f')
    time.sleep(0.2)
    pyautogui.typewrite(os)
    time.sleep(2)
    teste = driver.find_element(By.XPATH, "//*[@id='docs-findbar-input']/table/tbody/tr/td[2]/span").text
    print(os, teste)
    

    if teste == '1 de 1':
        time.sleep(0.5)
        pyautogui.press("enter")
        time.sleep(0.3)
        pyautogui.press("esc")
        time.sleep(0.1)
        pyautogui.press("tab")
        pyautogui.press("tab")
        pyautogui.press("tab")
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(today)
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(qtd)
        pyautogui.press("enter")
        time.sleep(0.1)
        pyautogui.hotkey("ctrl", "home")
        time.sleep(1)
    elif teste == '1 de 2':
        time.sleep(0.5)
        pyautogui.press("enter")
        time.sleep(0.3)
        pyautogui.press("esc")
        time.sleep(0.1)
        pyautogui.press("tab")
        pyautogui.press("tab")
        pyautogui.press("tab")
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(today)
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(qtd)
        pyautogui.press("enter")
        time.sleep(0.1)
        pyautogui.hotkey("ctrl", "home")
        time.sleep(1)
    elif teste == '1 de 3':
        time.sleep(0.5)
        pyautogui.press("enter")
        time.sleep(0.1)
        pyautogui.press("enter")
        time.sleep(0.3)
        pyautogui.press("esc")
        time.sleep(0.1)
        pyautogui.press("tab")
        pyautogui.press("tab")
        pyautogui.press("tab")
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(today)
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(qtd)
        pyautogui.press("enter")
        time.sleep(0.1)
        pyautogui.hotkey("ctrl", "home")
        time.sleep(1)
    elif teste == '2 de 2':
        time.sleep(0.5)
        pyautogui.press("enter")
        time.sleep(0.3)
        pyautogui.press("esc")
        time.sleep(0.1)
        pyautogui.press("tab")
        pyautogui.press("tab")
        pyautogui.press("tab")
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(today)
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(qtd)
        pyautogui.press("enter")
        time.sleep(0.1)
        pyautogui.hotkey("ctrl", "home")
        time.sleep(1)
    elif teste == '0 de 0':
        time.sleep(0.5)
        pyautogui.press("esc")
        time.sleep(0.1)
        pyautogui.hotkey("ctrl", "home")
        time.sleep(0.1)
        pyautogui.hotkey("ctrl", "down")
        time.sleep(0.1)
        pyautogui.press("down")
        time.sleep(0.1)
        linha = driver.find_element(By.ID, "t-name-box").get_attribute('value')
        linha = linha[1:]
        time.sleep(0.1)
        fiscal = fiscal.upper()
        pyautogui.typewrite(fiscal)
        time.sleep(0.1)
        pyautogui.press("tab")
        pyautogui.typewrite(ra)        
        pyautogui.press("tab")
        pyautogui.typewrite(os)
        time.sleep(0.1)
        pyautogui.press("tab")
        pyautogui.typewrite('VERIF. COND. FIS. HD')
        time.sleep(0.1)
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(yesterday)
        time.sleep(0.1)
        pyautogui.press("tab")
        time.sleep(0.1)        
        pyautogui.typewrite('=SE(G{}>=1;"DEVOLVIDA";SE(L{}="NAO PEGOU";"NAO EXECUTADA";"EM CAMPO"))'.format(linha, linha).upper())
        time.sleep(0.1)
        pyautogui.press("tab")        
        time.sleep(0.1)
        pyautogui.typewrite(today)
        time.sleep(0.1)
        pyautogui.press("tab")
        time.sleep(0.1)
        pyautogui.typewrite(qtd)
        time.sleep(0.3)
        pyautogui.press("enter")
        time.sleep(0.1)
        pyautogui.hotkey("ctrl", "home")
        time.sleep(1)