from datetime import date
from selenium.webdriver.common.by import By
import pandas as pd
from login import murilo, driver
from arquivos import prog_fisc
from fiscais import nomes, fiscais

df = pd.read_csv(prog_fisc)

dia_prog = date.today()
today2 = date.today()
dia_prog = dia_prog.strftime("%d/%m/%Y")
dia_prog = "09/08/2023"

fiscal_origem = "CAEMA-CADASTRO SEDE"
fiscal_origem1 = "CAEMACADASTROSEDE"

murilo()

driver.get("http://gsan.caema.ma.gov.br:8080/gsan/exibirAcompanharRoteiroProgramacaoOrdemServicoAction.do?menu=sim&filtro=0&dataRoteiro={}".format(dia_prog))


for i in df.index:
    try:
        driver.find_element(By.PARTIAL_LINK_TEXT, fiscal_origem).click()
        driver.find_element(By.XPATH, "//input[@value='{}___{}']".format(str(df['OS'][i]), str(df['FISCAL'][i]))).click()

    except:
        pass
    driver.find_element(By.NAME, "ButtonInformarSituacao").click()
    janela1 = driver.window_handles[0]
    popup = driver.window_handles[1]
    driver.switch_to.window(popup)
    driver.find_element(By.NAME, "situacaoOrdemServico").send_keys('PENDENTES')
    driver.find_element(By.XPATH, "//input[@value='Concluir']").click()
    driver.switch_to.window(janela1)

'''
230	ABIR DE R MESQUITA ABIRDERMESQUITA
244	ALEXSANDRO A MENDES	ALEXSANDROAMENDES
263	ANSELMO R MARQUES	ANSELMORMARQUES
245	ARCELINO JOSE DA SIL	ARCELINOJOSEDASIL
239	ARMANDO H ABREU	ARMANDOHABREU
246	AURELIO M F FILHO	AURELIOMFFILHO
247	BRASILIANO ALMEIDA	BRASILIANOALMEIDA
11	CAEMA-CADASTRO SEDE	CAEMA-CADASTROSEDE
231	CELSO H M RODRIGUES	CELSOHMRODRIGUES
248	CESAR L A FONSECA	CESARLAFONSECA
249	CLEITON ABREU MORAES	CLEITONABREUMORAES
250	DIMAS DIAS COSTA	DIMASDIASCOSTA
309	DOMINGOS LOPES DA SI	DOMINGOSLOPESDASI
251	ELIANE CONDE SANTOS	ELIANECONDESANTOS
223	EQUIPE ALLSAN/CAD	EQUIPEALLSAN/CAD
222	EQUIPE ESAC/CAD	EQUIPEESAC/CAD
253	FRANCISCO ARNOBIO	FRANCISCOARNOBIO
254	JADIEL RIBEIRO REIS	JADIELRIBEIROREIS
255	JOAO CARLOS R FONSEC	JOAOCARLOSRFONSEC
234	JOHNNY FRAN C SANTOS	JOHNNYFRANCSANTOS
308	JOSE BENEDITO PINTO	JOSEBENEDITOPINTO
235	JOSE DE RIBAMAR NUNE	JOSEDERIBAMARNUNE
264	JOSE DOMINGOS S FILH	JOSEDOMINGOSSFILH
256	JOSENILTON D DIAS	JOSENILTONDDIAS
242	JOSE PATRICIO S SILV	JOSEPATRICIOSSILV
243	JOSE R DINIZ MARANHA	JOSERDINIZMARANHA
267	JOSINALDO BARBOSA	JOSINALDOBARBOSA
257	LEONARDO C SANTIAGO	LEONARDOCSANTIAGO
258	LUIS ANTONIO A MOURA	LUISANTONIOAMOURA
236	LUIZ CARLOS FRAZAO	LUIZCARLOSFRAZAO
237	LUIZITO GEMA LIMA	LUIZITOGEMALIMA
259	MARCELO C PEREIRA	MARCELOCPEREIRA
260	MAURO HENRIQUE LIMA	MAUROHENRIQUELIMA
238	PEDRO SODRE COSTA F	PEDROSODRECOSTAF
240	RAIMUNDO N SANTOS	RAIMUNDONSANTOS
241	RAIMUNDO N S GONCALV	RAIMUNDONSGONCALV
261	RAMES MARTINS GARCIA	RAMESMARTINSGARCIA
272	THIAGO CHRISTOPHER	THIAGOCHRISTOPHER

230	ABIR DE R MESQUITA
244	ALEXSANDRO A MENDES
263	ANSELMO R MARQUES
245	ARCELINO JOSE DA SIL
239	ARMANDO H ABREU
246	AURELIO M F FILHO
247	BRASILIANO ALMEIDA
11	CAEMA-CADASTRO SEDE
231	CELSO H M RODRIGUES
248	CESAR L A FONSECA
249	CLEITON ABREU MORAES
250	DIMAS DIAS COSTA
309	DOMINGOS LOPES DA SI
251	ELIANE CONDE SANTOS
223	EQUIPE ALLSAN/CAD
222	EQUIPE ESAC/CAD
253	FRANCISCO ARNOBIO
254	JADIEL RIBEIRO REIS
255	JOAO CARLOS R FONSEC
234	JOHNNY FRAN C SANTOS
308	JOSE BENEDITO PINTO
235	JOSE DE RIBAMAR NUNE
264	JOSE DOMINGOS S FILH
256	JOSENILTON D DIAS
242	JOSE PATRICIO S SILV
243	JOSE R DINIZ MARANHA
267	JOSINALDO BARBOSA
257	LEONARDO C SANTIAGO
258	LUIS ANTONIO A MOURA
236	LUIZ CARLOS FRAZAO
237	LUIZITO GEMA LIMA
259	MARCELO C PEREIRA
260	MAURO HENRIQUE LIMA
238	PEDRO SODRE COSTA F
240	RAIMUNDO N SANTOS
241	RAIMUNDO N S GONCALV
261	RAMES MARTINS GARCIA
272	THIAGO CHRISTOPHER

ALEXSANDROAMENDES
ANSELMORMARQUES
ARCELINOJOSEDASIL
ARMANDOHABREU
AURELIOMFFILHO
BRASILIANOALMEIDA
CAEMA-CADASTROSEDE
CELSOHMRODRIGUES
CESARLAFONSECA
CLEITONABREUMORAES
DIMASDIASCOSTA
DOMINGOSLOPESDASI
ELIANECONDESANTOS
EQUIPEALLSAN/CAD
EQUIPEESAC/CAD
FRANCISCOARNOBIO
JADIELRIBEIROREIS
JOAOCARLOSRFONSEC
JOHNNYFRANCSANTOS
JOSEBENEDITOPINTO
JOSEDERIBAMARNUNE
JOSEDOMINGOSSFILH
JOSENILTONDDIAS
JOSEPATRICIOSSILV
JOSERDINIZMARANHA
JOSINALDOBARBOSA
LEONARDOCSANTIAGO
LUISANTONIOAMOURA
LUIZCARLOSFRAZAO
LUIZITOGEMALIMA
MARCELOCPEREIRA
MAUROHENRIQUELIMA
PEDROSODRECOSTAF
RAIMUNDONSANTOS
RAIMUNDONSGONCALV
RAMESMARTINSGARCIA
THIAGOCHRISTOPHER



'''